FROM node:20-alpine as build
WORKDIR /app
COPY . .

RUN npm install
RUN npm install react-router-dom
RUN npm uninstall tailwindcss
RUN npm install tailwindcss@3.4.1 postcss autoprefixer
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80