services:
  frontend:
    build:
      context: .  # ← root del progetto!
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env  # opzionale per runtime

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env  # Rende tutte le variabili disponibili
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userpwd
      MYSQL_DATABASE: HealthDB
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  ollama_data:
