services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: HealthDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpwd
    ports:
      - "5433:5432"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  ollama_data:
